server {
    listen 80;
    server_name ppventures.tech;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name ppventures.tech;

    ssl_certificate /etc/letsencrypt/live/ppventures.tech-0001/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/ppventures.tech-0001/privkey.pem;

    location / {
        return 301 https://ppventures.vercel.app$request_uri;
    }
}
