-- Disable RLS for easier development
ALTER TABLE agents DISABLE ROW LEVEL SECURITY;
ALTER TABLE tasks DISABLE ROW LEVEL SECURITY;
ALTER TABLE activity_logs DISABLE ROW LEVEL SECURITY;
ALTER TABLE cron_jobs DISABLE ROW LEVEL SECURITY;
